Port changes from C++ SDK to Rust SDK, add minor fixes
gluwa/sawtooth-legacy-sdk-rust pull request #1
Opened 2021-07-07 20:50 UTC by nathanwhit

2021-07-14 15:03 UTC, CAGS295 commented on protos/processor.proto
> +    uint64 tip = 6; // The block number
nitpick, keep comments style consistent.

2021-07-14 16:19 UTC, CAGS295 commented
[CRB-144]

2021-08-12 18:48 UTC, CAGS295 approved these changes

2021-08-12 18:48 UTC, CAGS295 commented
target `dev`

2021-09-21 18:48 UTC, CAGS295 commented
@atodorov do you want to add CI before I merge this PR?

2021-09-21 19:54 UTC, atodorov commented
> @atodorov do you want to add CI before I merge this PR?

Preferably yes, see #2. 

I've copied the test setup which they have in Jenkinsfile which uses containers. If that doesn't work then I'll look into something else, at least adding a compile & lint jobs for some sanity testing.

2021-09-22 08:44 UTC, atodorov requested changes, later dismissed
Please rebase so we can see the CI status.

2021-09-27 17:05 UTC, nathanwhit commented
Hm looks like CI failed with this line:
```
intkey-tp-rust_1       | Please build intkey-tp-rust first with 'docker-compose -f docker/compose/sawtooth-build.yaml up'
```
Not quite sure what to make of it at first glance, since I don't see any compilation failures or issues directly related to my changes. I'll look into it. cc @atodorov

2021-09-27 17:19 UTC, atodorov commented
> Hm looks like CI failed with this line:
> 
> ```
> intkey-tp-rust_1       | Please build intkey-tp-rust first with 'docker-compose -f docker/compose/sawtooth-build.yaml up'
> ```
> 
It's not that. This means the doker image we need hasn't been built but b/c the docker-compose file contains instructions for that it gets built on the fly. The error that I see is: 

```
2021-09-27T16:45:36.7436495Z [33mxo-tp-rust_1      |[0m [0;32m--- Building xo-tp-rust ---
2021-09-27T16:45:36.7449354Z [33mxo-tp-rust_1      |[0m [0m
2021-09-27T16:45:37.1687442Z [33mxo-tp-rust_1      |[0m     Updating crates.io index
2021-09-27T16:45:37.1774728Z [36mintkey-tp-rust_1  |[0m     Updating crates.io index
2021-09-27T16:45:54.8480836Z [33mxo-tp-rust_1      |[0m error: no matching package named `sawtooth-sdk` found
2021-09-27T16:45:54.8482033Z [33mxo-tp-rust_1      |[0m location searched: /project/sawtooth-sdk-rust
2021-09-27T16:45:54.8483397Z [33mxo-tp-rust_1      |[0m required by package `sawtooth-xo-tp-rust v0.5.2 (/project/sawtooth-sdk-rust/examples/xo_rust)`
2021-09-27T16:45:55.3990206Z [33m1279151612_xo-tp-rust_1 exited with code 101
2021-09-27T16:45:55.5078282Z [0m[36mintkey-tp-rust_1  |[0m error: no matching package named `sawtooth-sdk` found
```

Which could be a version mismatch from upstream or maybe using a newer version of the compiler.  

Definitely not related to your changes but ideally we'd like to see CI jobs passing before merging.

2021-09-27 17:29 UTC, nathanwhit commented
Whoops you're right, I was looking in the failed step, but the actual failure was in the step prior. I actually do know the cause of that (it's because the package is renamed so we avoid accidentally pulling the non forked SDK). Pushed a fix.

2021-09-27 21:50 UTC, nathanwhit commented
CI is green, so this just needs another review before merging.

2021-09-27 22:22 UTC, seandeneen-gluwa approved these changes

2021-09-27 23:58 UTC, merged